# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LC CV
email: caudevilla.louis@outlook.com
description:  # this means to ignore newlines until "baseurl:"
  My name is Louis Caudevilla, french and living in China. Young graduated business student looking for opportunites in Asia or in relation with China.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://louiscaudevilla.com" # the base hostname & protocol for your site
twitter_username: EssetiYapi
github_username:  esseter

# Build settings
markdown: kramdown
